{"ID":9532,"Author":{"Name":"konradkonrad","ID":0,"FullName":"","Gravatar":"605b9804b505e0de0ee1352cfc1737fc"},"Title":"zsh symlink execute problem","Description":"\u003cdiv class=\"content\"\u003e\u003cp\u003eI found an odd behavior with zsh: \u003c/p\u003e\n\n\u003cp\u003e\u003ccode\u003eautoload zsh-mime-setup; zsh-mime-setup\u003c/code\u003e sets \u003ccode\u003ealias -s py=zsh-mime-handler\u003c/code\u003e which leads to following problem:\u003c/p\u003e\n\n\u003cp\u003eIf I try to execute a \u003ccode\u003e#!/usr/bin/env python\u003c/code\u003e shebang-ed python script, it works well. But as soon as I symlink said script, and execute the symlink, it will try to open the file with \u003ccode\u003eless\u003c/code\u003e, as seems to be configured \u003ccode\u003ezsh-mime-setup -l|grep py\u003c/code\u003e.\u003c/p\u003e\n\n\u003cp\u003etl;dr;\u003cbr/\u003e\n\u003ccode\u003ezsh-mime-handler\u003c/code\u003e does not seem to handle symlinks of executables well.\u003c/p\u003e\n\n\u003cp\u003ezsh-Version:  4.3.17\u003c/p\u003e\n\n\u003cp\u003e[UPDATE] I found some context: apparently this was adressed in 2006 over at debian after 4.3.2-2: \u003ca href=\"https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=339635\"\u003ehttps://bugs.debian.org/cgi-bin/bugreport.cgi?bug=339635\u003c/a\u003e -- however it seems to still persist in 5.0.2 (see \u003ca href=\"https://asciinema.org/a/9533\"\u003ehttps://asciinema.org/a/9533\u003c/a\u003e)\u003c/p\u003e\n\u003c/div\u003e","Time":"2014-05-13T15:13:23Z","Tags":["Linux","bash","xterm"]}